# Generated by Django 3.1 on 2022-04-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_name', models.CharField(max_length=200, unique=True)),
                ('br_phonenumber', models.CharField(max_length=200, unique=True)),
                ('br_address', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClothesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=200, unique=True)),
                ('cate_description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_name', models.CharField(max_length=200, unique=True)),
                ('import_price', models.IntegerField()),
                ('clothes_description', models.TextField(blank=True, max_length=500)),
                ('clothesbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothesbrand')),
                ('clothescategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothescategory')),
            ],
        ),
    ]
