# Generated by Django 3.1 on 2022-05-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphoneitem',
            name='color',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
