# Generated by Django 3.1 on 2022-04-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_name', models.CharField(max_length=200, unique=True)),
                ('br_phonenumber', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopRAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_name', models.CharField(max_length=200, unique=True)),
                ('memory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_name', models.CharField(max_length=200, unique=True)),
                ('import_price', models.IntegerField()),
                ('chip', models.CharField(max_length=200, unique=True)),
                ('manufacturing_date', models.DateField()),
                ('laptopbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptopbrand')),
                ('laptopram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptopram')),
            ],
        ),
    ]
